title: Portfolio
name: Manmohan Gehlot
email: gehlot.21@gmail.com
description: Software engineer with hands-on experience in developing, designing and implementing strong backend system with best
industry practices. Supportive and enthusiastic team player dedicated to streamlining processes and efficiently resolving project
issues. Willing to take ownership of core components.

baseurl: "/blog"
url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: "Rate My Code"
project_one_description: A social media plateform, which rates your source code quality using static code quality evaluation.
project_one_url: https://github.com/mmgehlot/RateMyCode
project_one_icon: location_on

project_two: Second Project
project_two_description: Describe your project!
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera


project_three: Third Project
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel


project_four: Fourth Project
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: apache
  - name: debian
  - name: django
  - name: docker
  - name: git
  - name: itellij
  - name: java
  - name: javascript
  - name: linux
  - name: mongodb
  - name: mysql
  - name: nginx
  - name: nodejs
  - name: postgresql
  - name: python
  - name: pycharm
  - name: redis
  - name: ssh
  - name: ubuntu
  - name: vim
  - name: webstorm

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/mmgehlot
medium: https://medium.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: GTM-PHJDL55
google_analytics_tracking_id: UA-122934795-1 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
